<?php

namespace App\Model\SalarySheet;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use Illuminate\Database\Eloquent\SoftDeletes;

class CareemLimoSalarySheet extends Model  implements Auditable
{ 
    use \OwenIt\Auditing\Auditable;
    //

    public $table = "careem_limo_salaries";
    //

    protected $fillable=['driver_id',
        'driver_phone',
        'driver_name',
        'limo_id',
        'company_name',
        'payment_method',
        'total_driver_base_cost',
        'total_driver_other_cost',
        'total_driver_payment',
        'payable_amount',
        'combined_payment_company_part',
        'combined_payment_driver_part',
        'country',
        'city_name',
        'currency',
        'pay_date',
        'adj_trip_compensation',
        'adj_device_payment',
        'adj_salik',
        'adj_lost_device'
        ,'adj_bonus',
        'adj_sim_excess',
        'adj_last_month_adjustment',
        'adj_late_arrival',
        'adj_back_out',
        'adj_arrived_to_early',
        'adj_cash_collection',
        'adj_wrong_guest',
        'adj_cash_per_trip_payment',
        'adj_wire_fees',
        'adj_driver_tip',
        'adj_4h_guarantee',
        'adj_6h_guarantee',
        'adj_trip_referred_user',
        'adj_referred_driver_adjustment',
        'adj_referring_driver_adjustment',
        'adj_trip_by_referred_driver',
        'adj_data_plan_fees',
        'adj_fines',
        'adj_cash_paid_in_from_captain'
        ,'adj_wrong_amount_entered',
        'adj_health_insurance',
        'adj_items_bought',
        'adj_guarantee',
        'jordan_car_rental',
        'fawry',
        'captain_bonus',
        'referring_driver_trip_target_reward_amount',
        'referred_driver_trip_target_reward_amount',
        'cash_paid_in_by_captain_from_pos',
        'lease_deduction',
        'limo_commissions',
        'trainer_payment',
        'traffic_violation',
        'captain_careem_card',
        'one_time_card_payment',
        'rickshaw_adjustment',
        'card_operator_fees',
        'one_card_commission_deduction',
        'emergency_fund_deduction',
        'vendor_bonus_tax',
        'captain_bonus_tax',
        'uncollected_cash_for_trip',
        'past_trip_earning',
        'easypaisa_cash_collection',
        'captain_loyalty_program',
        'marketing_expenses',
        'packages_cash_collection',
        'madfooatcom_payment',
        'stc_cash_payment',
        'background_check',
        'fine_reimbursement',
        'pooling_trip_earnings',
        'switch_cash_payment',
        'top_up_commission',
        'quality_bonus',
        'midweek_paid_amount',
        'bonus_for_non_cash_trip',
        'refundable_deposit',
        'intercity_pooling_bonus',
        'captain_loyalty_trip_peak_bonus',
        'careempay_captain_debt_payment',
        'transfer_to_careempay',
        'now_cash_refusal',
        'vat_settlement_adjustment',
        'number_of_bank_details',
        'bank_wire_possible',
        'document_number',
        'date_from',
        'date_to',
        'file_path',
        'sheet_id',
    ];
}
